apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: status-page

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - gateway.yaml
  - auth.yaml
  - monitor.yaml
  - notify.yaml
  - dashboard.yaml
  - status.yaml
  - ingress.yaml
  - servicemonitor.yaml
