name: Build & Push API

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/api.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine tags
        id: tags
        run: |
          REPO_LOWER="${GITHUB_REPOSITORY,,}"
          BRANCH_LOWER="${GITHUB_REF_NAME,,}"

          if [ "$BRANCH_LOWER" = "main" ]; then
            echo "TAGS=ghcr.io/$REPO_LOWER/api:latest,ghcr.io/$REPO_LOWER/api:$GITHUB_SHA" >> $GITHUB_OUTPUT
          else
            echo "TAGS=ghcr.io/$REPO_LOWER/api:$BRANCH_LOWER,ghcr.io/$REPO_LOWER/api:$GITHUB_SHA" >> $GITHUB_OUTPUT
          fi

      - uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ${{ steps.tags.outputs.TAGS }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/api:latest
          cache-to: type=inline
