name: Build & Push App

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/app.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine tags
        id: tags
        run: |
          REPO_LOWER="${GITHUB_REPOSITORY,,}"
          BRANCH_LOWER="${GITHUB_REF_NAME,,}"

          if [ "$BRANCH_LOWER" = "main" ]; then
            echo "TAGS=ghcr.io/$REPO_LOWER/app:latest,ghcr.io/$REPO_LOWER/app:$GITHUB_SHA" >> $GITHUB_OUTPUT
          else
            echo "TAGS=ghcr.io/$REPO_LOWER/app:$BRANCH_LOWER,ghcr.io/$REPO_LOWER/app:$GITHUB_SHA" >> $GITHUB_OUTPUT
          fi

      - name: Build & Push App
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ steps.tags.outputs.TAGS }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/app:latest
          cache-to: type=inline
