name: Build and Deploy Docker Image

on:
  push:
    branches:
      - "*" # build on all branch pushes
  pull_request:
    branches:
      - "*"
  release:
    types: [published] # trigger on published releases

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: set_tag
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            # On release, tag = release tag
            TAG="${GITHUB_REF#refs/tags/}"
          elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            TAG="latest"
          elif [[ "${GITHUB_REF}" == refs/pull/* ]]; then
            PR_NUMBER=$(echo "${GITHUB_REF}" | grep -oP 'refs/pull/\K[0-9]+')
            TAG="pr-${PR_NUMBER}"
          else
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
            TAG="${BRANCH_NAME//\//-}"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build . \
            --tag ghcr.io/upayanmazumder/status-page:${{ env.TAG }} \
            --build-arg NODE_ENV=production

      - name: Push Docker Image (only on release)
        if: github.event_name == 'release'
        run: |
          docker push ghcr.io/upayanmazumder/status-page:${{ env.TAG }}
