name: Build and Deploy Docker Image on Release

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag from release
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker build . \
            --tag ghcr.io/upayanmazumder/status-page:${{ env.TAG }} \
            --build-arg NODE_ENV=production
          docker push ghcr.io/upayanmazumder/status-page:${{ env.TAG }}
